# -*- coding: utf-8 -*-
"""itch.io_testing_area

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLbVl3GxuVSDqHKaWx0xcHUw4mPqu7As
"""

import requests
from bs4 import BeautifulSoup
import json

main_url = "https://itch.io/game-assets/free/tag-3d"
response = requests.get(main_url)
soup = BeautifulSoup(response.text, "html.parser")
assets = []
found = 0
finder = soup.find_all("div", class_="game_cell")

for find in finder[:30]:
   the_links = find.find("a")["href"]
   the_img_links = find.find("img").get("data-lazy_src")
   the_athour = find.find("div", class_="game_author").text.strip()
   the_title = find.find("div", class_="game_title").text.strip()
   the_description = find.find("div", class_="game_text")

   asset = {"title" : the_title,"author" : the_athour,"img" : the_img_links,"link" : the_links, "description" : the_description.text.strip() if the_description else "no description"}
   assets.append(asset)

while True:
  search = input("search for assets: ")
  found = 0
  if search == "quit":
    break

  for asse in assets:
    if search.lower() in asse["description"].lower() or search.lower() in asse["title"].lower():
      found += 1
      print("=" * 30)
      print(f"Title: {asse['title']}")
      print(f"Author: {asse['author']}")
      print(f"Description: {asse['description']}")
      print(f"Link: {asse['link']}")
      print("=" * 30, "\n")
  if found <= 0:
    print("no results were found", "\n")

  print(f"Items found: {found}")