# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLbVl3GxuVSDqHKaWx0xcHUw4mPqu7As
"""

import requests
from bs4 import BeautifulSoup
import json
import os

assets = []

for page in range(1, 10):
  main_url = f"https://itch.io/game-assets/free/tag-3d?page={page}"
  response = requests.get(main_url)
  soup = BeautifulSoup(response.text, "html.parser")
  finder = soup.find_all("div", class_="game_cell")

  for find in finder:
    the_links = find.find("a")["href"]
    the_img_links = find.find("img").get("data-lazy_src")
    the_athour = find.find("div", class_="game_author").text.strip()
    the_title = find.find("div", class_="game_title").text.strip()
    the_description = find.find("div", class_="game_text")

    asset = {"title" : the_title,"author" : the_athour,"img" : the_img_links if the_img_links else "no image found" ,"link" : the_links, "description" : the_description.text.strip() if the_description else "no description"}
    assets.append(asset)

print(f"Total assets found ", len(assets))

while True:
  search = input("search for assets (or type quit): ")
  found = 0
  if search.lower() == "quit":
    break

  for asse in assets:
    if search.lower() in asse["description"].lower() or search.lower() in asse["title"].lower():
      found += 1
      print("=" * 30)
      print(f"Title: {asse['title']}")
      print(f"Author: {asse['author']}")
      print(f"Description: {asse['description']}")
      print(f"Link: {asse['link']}")
      print(f"Image : {asse['img']}")
      print("=" * 30, "\n")
  if found <= 0:
    print("no results were found", "\n")

  print(f"Items found: {found}")
  print(os.path.exists("assets.json"))

  with open("assets.json", "w") as file:
    json.dump(assets, file, indent=4)